export const VENTURES_A = [
  {
    name: "Thalo Cold",
    slug: "thalo-cold",
    sector: "Post-Harvest",
    stage: "growth",
    year: 2023,
    program: "RKVY",
    location: "Tezpur, AS",
    oneLiner: "Solar cold-chain micro-units for FPO-led aggregation. 14 nodes operational.",
    photoTreatment: "default",
    tagline: "Off-grid solar cold rooms parked at the collection point, so a smallholder's produce doesn't spoil before the buyer arrives.",
    website: "thalocold.in",
    founded: "Mar 2021",
    teamSize: 11,
    hq: "Tezpur, AS",
    status: "active",
    roundLabel: "Pre-Series A",
    roundDate: "Nov 2025",
    hiring: "3 open roles",
    investorContact: "rina@",
    facts: [
      { k: "Total raised", v: "₹1.4 Cr", sub: "incl. grant" },
      { k: "Nodes live", v: "14", sub: "across 3 districts" },
      { k: "FPOs served", v: "9", sub: "Sonitpur & Darrang" },
      { k: "Spoilage cut", v: "31%", sub: "post-installation" },
      { k: "Farmers reached", v: "2,300+", sub: "smallholders" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "A cold room that follows the harvest, not the grid" },
      { kind: "paragraph", text: "In the Brahmaputra valley, most vegetable losses happen in the first eight hours after picking. By the time produce reaches a mandi, the morning leaf crop has wilted and the buyer pays a distress price. Grid-tied cold storage exists in the towns, but it sits too far from the field and too far from the farmer's wallet." },
      { kind: "paragraph", text: "Thalo Cold builds small solar-powered cold rooms — roughly five tonnes each — that drop in at the FPO collection point itself. A unit runs entirely off rooftop panels with a thermal-battery backup for cloudy days, so an FPO in a fringe village can hold produce overnight without a diesel genset or a reliable line." },
      { kind: "paragraph", text: "The economics work because the FPO owns the aggregation, not Thalo. The company supplies, installs, and services the hardware on a subscription, then the producer collective decides what to chill and when to sell. That ownership split is what kept utilisation above 70 percent in the second season." },
      { kind: "figure", text: "Thalo Cold micro-unit at an FPO collection point near Dhekiajuli, panels mounted on the roof, crates of ridge gourd staged at the door.", cite: "Field photo, Sonitpur district, 2024" },
      { kind: "h3", text: "Why solar, and why this small" },
      { kind: "paragraph", text: "A larger central facility would have been cheaper per tonne on paper, but it would have forced farmers to truck produce twice. Keeping units small and distributed means the cold chain starts at the field edge — which is the only place the spoilage clock can actually be stopped." },
      { kind: "quote", text: "We stopped designing for the perfect district hub and started designing for the worst road. That decision is the whole company.", cite: "Rina Saikia · Co-founder & CEO" },
    ],
    founders: [
      { name: "Rina Saikia", role: "Co-founder & CEO", bio: "Mechanical engineer from Tezpur University who spent three seasons mapping post-harvest loss with KVK Sonitpur before starting Thalo. Grew up in a tea-belt family that ran a small vegetable plot.", photoTreatment: "default" },
      { name: "Pranjal Bora", role: "Co-founder & CTO", bio: "Refrigeration specialist trained at AAU Jorhat's agricultural engineering faculty. Built the first thermal-battery prototype in a borrowed Tezpur workshop.", photoTreatment: "tea" },
    ],
    milestones: [
      { when: "Mar 2021", what: "Founded in Tezpur", detail: "Two-person team, first sketch of the field-edge unit.", funded: false },
      { when: "Sep 2021", what: "Pilot unit at a Dhekiajuli FPO", detail: "Single five-tonne room, ridge gourd and leafy greens.", funded: false },
      { when: "Feb 2022", what: "RKVY RAFTAAR grant", detail: "NEATeHUB direct grant funded units two through five.", funded: true },
      { when: "Aug 2022", what: "Crossed 5 nodes", detail: "Expanded into Darrang with a second FPO partner.", funded: false },
      { when: "Jun 2023", what: "Saranya cohort, follow-on grant", detail: "NEATeHUB growth-stage support for the servicing fleet.", funded: true },
      { when: "Apr 2024", what: "14 nodes operational", detail: "Spoilage cut 31 percent across the network.", funded: false },
      { when: "Nov 2025", what: "Pre-Series A raise", detail: "₹1.1 Cr led by a regional climate fund.", funded: false },
    ],
    funding: [
      { round: "Grant", amount: "₹18 L", source: "RKVY · MoA&FW", neatehubRole: "Direct grant", date: "Feb 2022" },
      { round: "Grant", amount: "₹12 L", source: "RKVY · Saranya", neatehubRole: "Direct grant", date: "Jun 2023" },
      { round: "Seed", amount: "₹40 L", source: "Northeast Angel Syndicate", neatehubRole: "Introduced lead", date: "Jan 2024" },
      { round: "Pre-Series A", amount: "₹1.1 Cr", source: "Avaana Climate Fund", neatehubRole: "Co-investor intro", date: "Nov 2025" },
    ],
    engagement: {
      quote: "Thalo is the clearest case we have of hardware that earns its keep because the FPO owns the upside. We backed the servicing fleet, not just the boxes — that's what made the network stick.",
      manager: "Arnab Deka",
      role: "RKVY Program Manager, NEATeHUB",
      dates: "2022 – present",
      initials: "AD",
    },
    press: [
      { outlet: "Assam Tribune · Regional", headline: "Solar cold rooms cut vegetable losses in Sonitpur belt", date: "May 2024", url: "#" },
      { outlet: "The Sentinel · State", headline: "Tezpur startup takes cold chain to the field edge", date: "Sep 2024", url: "#" },
      { outlet: "Mint · National", headline: "Climate fund backs Assam post-harvest venture", date: "Nov 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY · Saranya '23", current: true },
      { label: "RKVY · Isanya '22", current: false },
    ],
    sdgs: [
      { num: "SDG 2", label: "Zero Hunger" },
      { num: "SDG 7", label: "Affordable & Clean Energy" },
      { num: "SDG 12", label: "Responsible Consumption" },
    ],
  },
  {
    name: "Brahma Aqua",
    slug: "brahma-aqua",
    sector: "Aqua",
    stage: "early",
    year: 2024,
    program: "AIC",
    location: "Guwahati, AS",
    oneLiner: "Indigenous fish-feed formulation. 30% cost reduction vs imports.",
    photoTreatment: "copper",
    tagline: "A floating fish feed milled from Assam's own oilcake and rice-bran by-products, priced for the pond owner who can't afford the imported pellet.",
    website: "brahmaaqua.in",
    founded: "Jul 2022",
    teamSize: 7,
    hq: "Guwahati, AS",
    status: "active",
    roundLabel: "Seed",
    roundDate: "Aug 2025",
    hiring: "2 open roles",
    investorContact: "deep@",
    facts: [
      { k: "Total raised", v: "₹62 L", sub: "incl. grant" },
      { k: "Cost vs import", v: "−30%", sub: "per kg, floating pellet" },
      { k: "Ponds supplied", v: "180+", sub: "Kamrup & Nalbari" },
      { k: "FCR", v: "1.4", sub: "field-trialled" },
      { k: "Local inputs", v: "82%", sub: "by raw-material weight" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Fish feed that doesn't have to come from a port" },
      { kind: "paragraph", text: "Assam imports most of its aquaculture feed, and the freight alone prices smallholder pond owners out of the better pellets. They end up using kitchen scraps or low-grade mash, the fish grow slowly, and the margin disappears. Feed is the single largest cost in pond farming, and it was the one cost nobody local controlled." },
      { kind: "paragraph", text: "Brahma Aqua formulates a floating pellet from regional by-products — mustard oilcake, de-oiled rice bran, and a protein blend the team developed with the College of Fisheries at AAU. It hits the protein and buoyancy targets of an imported feed while sourcing more than four-fifths of its raw material from within the state." },
      { kind: "paragraph", text: "The thirty percent cost cut isn't a discount; it's the freight and the importer's margin removed from the chain. Field trials in Kamrup put feed-conversion at 1.4, close enough to imported pellets that pond owners stopped switching back." },
      { kind: "figure", text: "Brahma Aqua floating pellets being broadcast over a community pond near Hajo, fish surfacing at the feed line.", cite: "Field trial, Kamrup district, 2024" },
      { kind: "h3", text: "Built with the fisheries college, not around it" },
      { kind: "paragraph", text: "The formulation came out of a year of joint trials with ICAR and the AAU fisheries faculty. That partnership is what let a young company make a credible nutrition claim — the data was independent, and the pond owners trusted it." },
      { kind: "quote", text: "Every rupee of feed cost we take out is a rupee the pond owner keeps. That's the entire pitch, and it's enough.", cite: "Deepjyoti Nath · Co-founder" },
    ],
    founders: [
      { name: "Deepjyoti Nath", role: "Co-founder & CEO", bio: "Fisheries science graduate from the College of Fisheries, AAU, who ran extension work across Kamrup before founding the company. Comes from a Nalbari family that has farmed ponds for three generations.", photoTreatment: "copper" },
    ],
    milestones: [
      { when: "Jul 2022", what: "Founded in Guwahati", detail: "First formulation batch milled by hand.", funded: false },
      { when: "Jan 2023", what: "Joint trials with ICAR & AAU", detail: "Nutrition and buoyancy validation over two seasons.", funded: false },
      { when: "Sep 2023", what: "AIC incubation", detail: "NITI Aayog Atal Incubation Centre cohort at NEATeHUB.", funded: false },
      { when: "Mar 2024", what: "AIC seed grant", detail: "NEATeHUB grant funded the pilot pellet line.", funded: true },
      { when: "Aug 2024", what: "First 50 ponds supplied", detail: "Kamrup cluster, repeat orders within one cycle.", funded: false },
      { when: "Feb 2025", what: "Second grant tranche", detail: "NEATeHUB scale-up grant for milling capacity.", funded: true },
      { when: "Aug 2025", what: "Seed round closed", detail: "₹45 L from an agri-focused micro-fund.", funded: false },
    ],
    funding: [
      { round: "Grant", amount: "₹10 L", source: "AIC · NITI Aayog", neatehubRole: "Direct grant", date: "Mar 2024" },
      { round: "Grant", amount: "₹7 L", source: "AIC · NITI Aayog", neatehubRole: "Direct grant", date: "Feb 2025" },
      { round: "Seed", amount: "₹45 L", source: "Ahimsa Capital", neatehubRole: "Introduced lead", date: "Aug 2025" },
    ],
    engagement: {
      quote: "Brahma Aqua won us over because the founder refused to make a nutrition claim he couldn't back with ICAR data. We funded the pellet line knowing the science was already independent.",
      manager: "Sunita Phukan",
      role: "AIC Incubation Manager, NEATeHUB",
      dates: "2023 – present",
      initials: "SP",
    },
    press: [
      { outlet: "The Sentinel · State", headline: "Guwahati startup mills fish feed from local oilcake", date: "Oct 2024", url: "#" },
      { outlet: "Assam Tribune · Regional", headline: "Indigenous feed cuts pond-farming costs by a third", date: "Jan 2025", url: "#" },
      { outlet: "Northeast Now · Regional", headline: "AIC-backed aqua venture closes seed round", date: "Aug 2025", url: "#" },
    ],
    programTags: [
      { label: "AIC · Cohort '23", current: true },
    ],
    sdgs: [
      { num: "SDG 2", label: "Zero Hunger" },
      { num: "SDG 14", label: "Life Below Water" },
    ],
  },
  {
    name: "Mati Labs",
    slug: "mati-labs",
    sector: "Agri-Input",
    stage: "idea",
    year: 2025,
    program: "Isanya",
    location: "Jorhat, AS",
    oneLiner: "Mobile soil-testing rig for KVKs. ₹40 per test, 14-min turnaround.",
    photoTreatment: "default",
    tagline: "A briefcase-sized soil lab a KVK officer can carry to the village and hand a farmer a full nutrient card before tea goes cold.",
    website: "matilabs.in",
    founded: "Jan 2025",
    teamSize: 4,
    hq: "Jorhat, AS",
    status: "active",
    roundLabel: "Grant-funded",
    roundDate: "Apr 2025",
    hiring: "1 open role",
    investorContact: "bhargav@",
    facts: [
      { k: "Cost per test", v: "₹40", sub: "vs ₹250 lab" },
      { k: "Turnaround", v: "14 min", sub: "field result" },
      { k: "Parameters", v: "7", sub: "N-P-K, pH, OC + 2" },
      { k: "KVKs piloting", v: "3", sub: "Jorhat & Golaghat" },
      { k: "Samples run", v: "600+", sub: "validation phase" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "A soil lab that fits in a KVK officer's bag" },
      { kind: "paragraph", text: "A soil health card is only useful if it arrives while the farmer is still deciding what to sow. Send a sample to a district lab and the result comes back two to three weeks later, often after the window has closed. Most smallholders simply skip the test and fertilise by habit, which is how the valley ended up over-applying urea for years." },
      { kind: "paragraph", text: "Mati Labs is building a portable rig — colourimetric cartridges plus a phone-based reader — that a KVK extension officer can run in the field. Seven parameters, fourteen minutes, and a printed nutrient card in the farmer's hand before the conversation ends. At forty rupees a test it's cheap enough for a KVK to offer it at scale." },
      { kind: "paragraph", text: "The venture is still at idea stage; the rig is in its second prototype and the team is in the Isanya residential cohort. The current focus is reliability across Assam's high-organic-carbon soils, where standard kits drift, not commercial rollout." },
      { kind: "figure", text: "Mati Labs prototype rig open on a stool at a Jorhat village demo, cartridge tray and phone reader, a farmer watching the result print.", cite: "Isanya residency demo, Jorhat, 2025" },
      { kind: "h3", text: "Calibrated for valley soils, not a generic kit" },
      { kind: "paragraph", text: "Off-the-shelf field kits are calibrated for drier soils and misread the organic carbon common in the Brahmaputra valley. The team is rebuilding the colourimetric reference against AAU soil-science datasets so the card a farmer gets is actually right for their plot." },
      { kind: "quote", text: "The lab result was always correct and always too late. We're not making it more accurate, we're making it arrive in time.", cite: "Bhargav Hazarika · Founder" },
    ],
    founders: [
      { name: "Bhargav Hazarika", role: "Founder", bio: "Soil science postgraduate from AAU Jorhat who worked a season with a KVK and watched soil cards arrive after sowing. Building Mati to close that gap.", photoTreatment: "default" },
      { name: "Ankita Gogoi", role: "Co-founder, Hardware", bio: "Electronics engineer from Jorhat Engineering College who designed the cartridge reader. Earlier built low-cost diagnostic tools at a Tezpur University maker lab.", photoTreatment: "copper" },
    ],
    milestones: [
      { when: "Jan 2025", what: "Founded in Jorhat", detail: "Two founders, first colourimetric breadboard.", funded: false },
      { when: "Feb 2025", what: "Isanya residency", detail: "Selected for NEATeHUB's residential idea-stage cohort.", funded: false },
      { when: "Apr 2025", what: "Isanya seed grant", detail: "NEATeHUB direct grant for the second prototype.", funded: true },
      { when: "May 2025", what: "First KVK pilot", detail: "Jorhat KVK ran 200 samples against lab reference.", funded: false },
      { when: "Jul 2025", what: "Validation grant", detail: "NEATeHUB follow-on for soil-science calibration work.", funded: true },
      { when: "Sep 2025", what: "600 samples run", detail: "Expanded pilot to Golaghat across three KVKs.", funded: false },
    ],
    funding: [
      { round: "Grant", amount: "₹6 L", source: "RKVY · Isanya", neatehubRole: "Direct grant", date: "Apr 2025" },
      { round: "Grant", amount: "₹4 L", source: "RKVY · Isanya", neatehubRole: "Direct grant", date: "Jul 2025" },
      { round: "Pre-seed", amount: "₹8 L", source: "AAU Innovation Fund", neatehubRole: "Introduced lead", date: "Oct 2025" },
    ],
    engagement: {
      quote: "Mati is exactly what Isanya is for — a real field problem, a founder who lived it, and a prototype rough enough that grant money changes the trajectory. We're backing the calibration, which is the hard part.",
      manager: "Rituraj Saikia",
      role: "Isanya Residency Lead, NEATeHUB",
      dates: "2025 – present",
      initials: "RS",
    },
    press: [
      { outlet: "Assam Tribune · Regional", headline: "Jorhat team builds 14-minute field soil test", date: "Jun 2025", url: "#" },
      { outlet: "The Assam Express · State", headline: "Isanya cohort startup pilots ₹40 soil card with KVKs", date: "Aug 2025", url: "#" },
      { outlet: "EastMojo · Regional", headline: "Portable soil lab targets Brahmaputra valley farmers", date: "Sep 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY · Isanya '25", current: true },
    ],
    sdgs: [
      { num: "SDG 2", label: "Zero Hunger" },
      { num: "SDG 15", label: "Life on Land" },
    ],
  },
  {
    name: "Eri Threads",
    slug: "eri-threads",
    sector: "Food",
    stage: "early",
    year: 2023,
    program: "ASRLM",
    location: "Sualkuchi, AS",
    oneLiner: "Eri silk by-product proteins for nutraceutical use. Producer-owned.",
    photoTreatment: "tea",
    tagline: "Turning the pupae and waste that Sualkuchi's eri-silk reelers used to throw away into a food-grade protein the weaving collectives own.",
    website: "erithreads.in",
    founded: "May 2021",
    teamSize: 9,
    hq: "Sualkuchi, AS",
    status: "active",
    roundLabel: "Grant-funded",
    roundDate: "Jun 2025",
    hiring: "Not hiring",
    investorContact: "junmoni@",
    facts: [
      { k: "Total raised", v: "₹38 L", sub: "incl. grant" },
      { k: "SHGs onboarded", v: "22", sub: "Sualkuchi cluster" },
      { k: "Waste recovered", v: "60%", sub: "of reeling by-product" },
      { k: "Protein yield", v: "48%", sub: "by dry weight" },
      { k: "Women earners", v: "260+", sub: "producer-members" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "The waste from the loom, turned into food-grade protein" },
      { kind: "paragraph", text: "Eri silk is reeled without killing the moth, which is part of what makes Sualkuchi's weaving culture distinct. But the process leaves behind pupae and spent cocoon matter that the reeling households simply discarded — a steady stream of high-protein biomass treated as refuse for generations." },
      { kind: "paragraph", text: "Eri Threads recovers that by-product and processes it into a food-grade protein powder for the nutraceutical market. Eri pupae are already eaten in parts of the Northeast, so the nutritional case was never in doubt; the work was building a clean, standardised extraction that a buyer outside the region would accept." },
      { kind: "paragraph", text: "The company is structured so the weaving collectives own it. Sourced through ASRLM self-help groups, the by-product becomes a second income for households that previously earned only from the cloth. The protein revenue flows back to the producer-members, not to an outside processor." },
      { kind: "figure", text: "Women from a Sualkuchi SHG sorting eri cocoon by-product at the collective's processing shed, trays of dried pupae in the foreground.", cite: "Producer collective, Sualkuchi, 2024" },
      { kind: "h3", text: "Producer-owned, by design" },
      { kind: "paragraph", text: "Routing everything through ASRLM self-help groups was a deliberate choice, not a compliance step. It meant the value of the recovered waste stayed inside the weaving cluster — the same households, a second income — rather than being extracted by a processor who happened to spot the opportunity first." },
      { kind: "quote", text: "The protein was always there in the waste. What we built was a way for the women who reel the silk to be the ones who own it.", cite: "Junmoni Das · Co-founder" },
    ],
    founders: [
      { name: "Junmoni Das", role: "Co-founder & CEO", bio: "Food technologist from Tezpur University, born into a Sualkuchi weaving family. Spent two years on extraction protocols before the collective model came together.", photoTreatment: "tea" },
      { name: "Nabajit Kalita", role: "Co-founder, Operations", bio: "Sericulture specialist trained with the Central Silk Board who ran ASRLM cluster work across Kamrup. Manages the SHG sourcing network.", photoTreatment: "default" },
    ],
    milestones: [
      { when: "May 2021", what: "Founded in Sualkuchi", detail: "First extraction trials in a rented shed.", funded: false },
      { when: "Dec 2021", what: "ASRLM SHG partnership", detail: "First eight self-help groups onboarded for sourcing.", funded: false },
      { when: "Aug 2022", what: "ASRLM livelihood grant", detail: "NEATeHUB grant funded the producer-owned processing unit.", funded: true },
      { when: "Apr 2023", what: "Food-grade certification", detail: "Standardised protein passed external lab assay.", funded: false },
      { when: "Nov 2023", what: "22 SHGs onboarded", detail: "Cluster reached 260 women producer-members.", funded: false },
      { when: "Jun 2025", what: "Scale-up grant", detail: "NEATeHUB follow-on for drying and packaging capacity.", funded: true },
    ],
    funding: [
      { round: "Grant", amount: "₹14 L", source: "ASRLM · State Livelihoods", neatehubRole: "Direct grant", date: "Aug 2022" },
      { round: "Grant", amount: "₹9 L", source: "ASRLM · State Livelihoods", neatehubRole: "Direct grant", date: "Jun 2025" },
      { round: "Seed", amount: "₹15 L", source: "Villgro Northeast", neatehubRole: "Introduced lead", date: "Mar 2024" },
    ],
    engagement: {
      quote: "Eri Threads is the kind of venture ASRLM exists to back — a producer-owned model where recovered waste becomes a women's income. We funded the processing unit so the value would stay in the cluster.",
      manager: "Mridula Bezbaruah",
      role: "ASRLM Program Manager, NEATeHUB",
      dates: "2022 – present",
      initials: "MB",
    },
    press: [
      { outlet: "Assam Tribune · Regional", headline: "Sualkuchi collective turns eri-silk waste into protein", date: "Feb 2024", url: "#" },
      { outlet: "The Sentinel · State", headline: "Producer-owned nutraceutical venture grows in weaving belt", date: "Jul 2024", url: "#" },
      { outlet: "EastMojo · Regional", headline: "ASRLM-backed startup gives women a second income from silk", date: "Jun 2025", url: "#" },
    ],
    programTags: [
      { label: "ASRLM · Cohort '23", current: true },
      { label: "ASRLM · Cohort '22", current: false },
    ],
    sdgs: [
      { num: "SDG 5", label: "Gender Equality" },
      { num: "SDG 8", label: "Decent Work & Growth" },
      { num: "SDG 12", label: "Responsible Consumption" },
    ],
  },
];
