export const VENTURES_C = [
  {
    name: "Pukhuri Fish",
    slug: "pukhuri-fish",
    sector: "Aqua",
    stage: "idea",
    year: 2025,
    program: "Isanya",
    location: "Nagaon, AS",
    oneLiner: "Pond-based aquaculture sensor pack. Pilot with 200 ponds.",
    photoTreatment: "tea",
    tagline: "A low-cost sensor pack that tells smallholder fish farmers when their pond is about to crash.",
    website: "pukhurifish.in",
    founded: "Feb 2025",
    teamSize: 6,
    hq: "Nagaon, AS",
    status: "active",
    roundLabel: "Grant-funded",
    roundDate: "Mar 2025",
    hiring: "2 open roles",
    investorContact: "rituparna@",
    facts: [
      { k: "Ponds on pilot", v: "200", sub: "across 14 villages in Nagaon district" },
      { k: "Sensor cost", v: "₹2,400", sub: "per pond, vs ₹18,000 for imported probes" },
      { k: "Crash alerts sent", v: "61", sub: "dissolved-oxygen warnings in first season" },
      { k: "Avg holding size", v: "0.4 ha", sub: "typical beel-fed family pond" },
      { k: "Battery life", v: "9 months", sub: "single solar-charged cell per unit" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Reading a pond before it turns" },
      { kind: "paragraph", text: "Most fish deaths in Assam's family ponds happen overnight, when dissolved oxygen drops and nobody is awake to see it. By morning a farmer can lose half a season's stock. Pukhuri Fish builds a floating sensor pack that measures oxygen, temperature and turbidity every fifteen minutes and pushes a plain-language alert to the farmer's phone." },
      { kind: "paragraph", text: "The team deliberately stripped the hardware down. Imported aquaculture probes cost more than a year of a smallholder's profit, so they redesigned around a single solar cell, a cheap optical oxygen sensor and an SMS fallback for villages with weak data coverage. The pilot runs on 200 ponds in Nagaon, most of them under half a hectare." },
      { kind: "figure", text: "A sensor float being calibrated against a manual DO meter at a Nagaon demonstration pond.", cite: "NEATeHUB field log, March 2025" },
      { kind: "h3", text: "Why idea stage, not later" },
      { kind: "paragraph", text: "The product works, but the unit economics still depend on getting manufacturing below ₹2,000 and proving farmers will pay a small annual fee. That is the question the Isanya residency is built to answer, so the venture is intentionally still at idea stage." },
      { kind: "quote", text: "We are not trying to teach people aquaculture. They have done this for generations. We are just giving them one night's warning.", cite: "Rituparna Saikia · Founder" },
    ],
    founders: [
      {
        name: "Rituparna Saikia",
        role: "Founder & CEO",
        bio: "Grew up in a fishing-pond household near Nagaon and trained in instrumentation at Assam Engineering College. Spent three years maintaining water-quality rigs for a Guwahati municipal lab before returning home to build for the ponds she knew.",
        photoTreatment: "tea",
      },
      {
        name: "Hemanta Bordoloi",
        role: "Co-founder, Field & Farmer Ops",
        bio: "An ASRLM community resource person from Morigaon who has organised pond-farmer collectives for over a decade. Handles enrolment, training and the trust-building that gets a sensor onto a stranger's pond.",
        photoTreatment: "default",
      },
    ],
    milestones: [
      { when: "Feb 2025", what: "Venture founded", detail: "Spun out of a college instrumentation project after a kill event wiped out a neighbour's stock.", funded: false },
      { when: "Mar 2025", what: "Isanya residency seed grant", detail: "Selected into the residential idea-stage cohort with a first build grant.", funded: true },
      { when: "Apr 2025", what: "First 30 ponds instrumented", detail: "Deployed across three villages to validate the optical oxygen reading against manual meters.", funded: false },
      { when: "Jun 2025", what: "SMS fallback shipped", detail: "Added low-bandwidth alerts after data coverage gaps in beel-side villages.", funded: false },
      { when: "Aug 2025", what: "Scaled to 200-pond pilot", detail: "Expanded to 14 villages with a NEATeHUB hardware-iteration grant.", funded: true },
      { when: "Oct 2025", what: "61 verified crash alerts", detail: "Independently confirmed early-warning events over the monsoon season.", funded: false },
    ],
    funding: [
      { round: "Idea grant", amount: "₹6,00,000", source: "RKVY RAFTAAR · Isanya", neatehubRole: "Lead grant & residency", date: "Mar 2025" },
      { round: "Hardware iteration grant", amount: "₹4,50,000", source: "NEATeHUB innovation fund", neatehubRole: "Direct disbursing body", date: "Aug 2025" },
      { round: "Pilot support", amount: "₹3,20,000", source: "ASRLM convergence", neatehubRole: "Convergence facilitator", date: "Sep 2025" },
    ],
    engagement: {
      quote: "Pukhuri is the cleanest example we have of hardware built to a farmer's actual wallet, not a lab's spec sheet. The residency is about pricing now, not proving.",
      manager: "Anindita Hazarika",
      role: "Programme Manager, Isanya",
      dates: "Mar 2025 — present",
      initials: "AH",
    },
    press: [
      { outlet: "The Assam Tribune", headline: "Nagaon team builds budget sensors to stop overnight fish kills", date: "May 2025", url: "#" },
      { outlet: "EastMojo", headline: "Can a ₹2,400 float save Assam's pond farmers a season?", date: "Jul 2025", url: "#" },
      { outlet: "Down To Earth", headline: "Frugal aquaculture sensing finds early traction in the Northeast", date: "Sep 2025", url: "#" },
    ],
    programTags: [
      { label: "Isanya · Idea stage", current: true },
    ],
    sdgs: [
      { num: 2, label: "Zero Hunger" },
      { num: 12, label: "Responsible Consumption" },
      { num: 14, label: "Life Below Water" },
    ],
  },
  {
    name: "Bambusa Build",
    slug: "bambusa-build",
    sector: "Agri-Input",
    stage: "growth",
    year: 2021,
    program: "RKVY · AIC",
    location: "Imphal, MN",
    oneLiner: "Engineered bamboo for agri-shelter construction. 2,300 units shipped.",
    photoTreatment: "default",
    tagline: "Treated, engineered bamboo panels that let farmers raise drying yards and livestock sheds without steel.",
    website: "bambusabuild.in",
    founded: "Jun 2019",
    teamSize: 41,
    hq: "Imphal, MN",
    status: "active",
    roundLabel: "Pre-Series A",
    roundDate: "Nov 2025",
    hiring: "4 open roles",
    investorContact: "thoiba@",
    facts: [
      { k: "Units shipped", v: "2,300", sub: "agri-shelters and drying yards since 2021" },
      { k: "States served", v: "5", sub: "Manipur, Nagaland, Mizoram, Assam, Meghalaya" },
      { k: "Bamboo sourced", v: "190 t/yr", sub: "from 600+ grower households" },
      { k: "Cost vs steel", v: "−38%", sub: "for a comparable 200 sq ft shelter" },
      { k: "Workshop staff", v: "41", sub: "two-thirds women on the treatment line" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Making bamboo behave like a building material" },
      { kind: "paragraph", text: "Bamboo is everywhere in Manipur and almost never used for anything that has to last, because untreated it splits, warps and is eaten within two seasons. Bambusa Build runs a borate treatment and lamination line that turns local bamboo into standardised panels and posts a farmer can bolt into a shelter, a poultry shed or a paddy drying yard." },
      { kind: "paragraph", text: "The company sells finished kits, not raw material. A farmer orders a shelter size, receives flat-packed panels with fittings, and raises it in a day without a welder. That packaging is what moved bamboo from a craft input to an agri-input, and it is why 2,300 units have shipped across five states." },
      { kind: "paragraph", text: "Supply is the harder half of the business. The team contracts with more than 600 grower households on a fixed seasonal rate, which gives farmers a cash crop off marginal land and gives the workshop a predictable feedstock." },
      { kind: "figure", text: "Flat-packed engineered-bamboo shelter panels staged for dispatch at the Imphal workshop.", cite: "Bambusa Build operations review, 2024" },
      { kind: "h3", text: "Where growth pressure sits now" },
      { kind: "paragraph", text: "Demand outruns the single Imphal line. The pre-Series A is meant to fund a second treatment unit in Dimapur and shorten delivery times into Nagaland and Assam, where freight currently eats the cost advantage." },
      { kind: "quote", text: "People here have always built with bamboo. We just made it boring and predictable, which is exactly what a farmer paying for a shed wants.", cite: "Thoiba Singh · Founder" },
    ],
    founders: [
      {
        name: "Thoiba Singh",
        role: "Founder & CEO",
        bio: "A civil engineer from Imphal who spent his early career on rural housing schemes across Manipur and grew frustrated watching bamboo rejected for lack of a standard. Started the treatment line in a rented shed in 2019.",
        photoTreatment: "default",
      },
      {
        name: "Sanahanbi Devi",
        role: "Co-founder & Head of Operations",
        bio: "Built and now runs the treatment and lamination floor, hiring and training a largely women workforce from villages around Bishnupur. Manages the grower-household supply contracts.",
        photoTreatment: "copper",
      },
    ],
    milestones: [
      { when: "Jun 2019", what: "Workshop founded", detail: "First borate treatment line set up in a rented shed outside Imphal.", funded: false },
      { when: "2021", what: "Entered NEATeHUB via RKVY", detail: "Joined the growth-stage cohort and received product-standardisation support.", funded: true },
      { when: "2022", what: "1,000th unit shipped", detail: "Crossed the first thousand agri-shelters, mostly within Manipur.", funded: false },
      { when: "2023", what: "AIC scale-up grant", detail: "Atal Incubation Centre grant funded the lamination upgrade and second product line.", funded: true },
      { when: "2024", what: "Five-state distribution", detail: "Opened dealer points in Nagaland, Mizoram, Assam and Meghalaya.", funded: false },
      { when: "Aug 2025", what: "2,300 units shipped", detail: "Reached cumulative milestone with 600+ grower households under contract.", funded: false },
      { when: "Nov 2025", what: "Pre-Series A opened", detail: "Raising to build a second treatment unit in Dimapur.", funded: false },
    ],
    funding: [
      { round: "Growth grant", amount: "₹12,00,000", source: "RKVY RAFTAAR", neatehubRole: "Lead grant & mentoring", date: "2021" },
      { round: "AIC scale-up grant", amount: "₹25,00,000", source: "AIM / Atal Incubation Centre", neatehubRole: "Host incubator & disbursing", date: "2023" },
      { round: "Working-capital debt", amount: "₹40,00,000", source: "NEDFi", neatehubRole: "Introduction & guarantee facilitation", date: "2024" },
      { round: "Pre-Series A", amount: "₹3,10,00,000", source: "Omnivore (lead) + angels", neatehubRole: "Diligence support & syndicate intro", date: "Nov 2025" },
    ],
    engagement: {
      quote: "Bambusa is the venture we point funders to when they ask what a deep supply chain in the hills looks like. The hard part was never the panel, it was 600 households trusting a price.",
      manager: "Romen Meitei",
      role: "Programme Manager, AIC",
      dates: "2021 — present",
      initials: "RM",
    },
    press: [
      { outlet: "The Hindu BusinessLine", headline: "Engineered bamboo finds a market in Northeast farm shelters", date: "Mar 2024", url: "#" },
      { outlet: "Imphal Free Press", headline: "Imphal workshop ships 2,000th bamboo agri-shelter", date: "Jan 2025", url: "#" },
      { outlet: "YourStory", headline: "Bambusa Build raises pre-Series A to scale bamboo construction", date: "Nov 2025", url: "#" },
      { outlet: "Mongabay India", headline: "A bamboo cash crop is reshaping marginal land in Manipur", date: "Dec 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY · Growth", current: false },
      { label: "AIC · Scale-up", current: true },
    ],
    sdgs: [
      { num: 8, label: "Decent Work & Growth" },
      { num: 9, label: "Industry & Infrastructure" },
      { num: 15, label: "Life on Land" },
    ],
  },
  {
    name: "Charai Foods",
    slug: "charai-foods",
    sector: "Food",
    stage: "early",
    year: 2023,
    program: "Saranya",
    location: "Agartala, TR",
    oneLiner: "Smoked-pork product line with FSSAI clearance and 6-state distribution.",
    photoTreatment: "copper",
    tagline: "Shelf-stable smoked pork that carries a Northeast kitchen staple beyond the home and into retail.",
    website: "charaifoods.in",
    founded: "Apr 2023",
    teamSize: 18,
    hq: "Agartala, TR",
    status: "active",
    roundLabel: "Seed",
    roundDate: "Jan 2026",
    hiring: "1 open role",
    investorContact: "lalruat@",
    facts: [
      { k: "States distributed", v: "6", sub: "across the Northeast plus Kolkata" },
      { k: "SKUs", v: "5", sub: "smoked, dry-cured and ready-to-cook" },
      { k: "Pigs sourced", v: "120/mo", sub: "from 80 backyard rearing households" },
      { k: "Shelf life", v: "120 days", sub: "ambient, no cold chain needed" },
      { k: "Retail points", v: "210", sub: "stores and online stockists" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Putting a smokehouse staple on a shelf" },
      { kind: "paragraph", text: "Smoked pork is a fixture in kitchens across Tripura, Mizoram and Nagaland, but it has almost no formal market. It is made at home, sold loose, and spoils fast. Charai Foods takes that same product, standardises the cure and smoke, and packages it as a shelf-stable, FSSAI-cleared line that can sit in a shop for four months without refrigeration." },
      { kind: "paragraph", text: "The hard technical problem was food safety. Traditional smoking is inconsistent, so the team built a controlled smokehouse and a dry-cure process that hits a reliable water-activity target, then carried it through FSSAI clearance. That certification is what let the product cross state lines into modern retail." },
      { kind: "paragraph", text: "Sourcing leans on backyard pig rearing, which is widespread but informal. Charai contracts roughly 80 households for a steady 120 pigs a month, giving rural rearers a buyer at a known price." },
      { kind: "figure", text: "Dry-cured smoked pork moving through the controlled smokehouse before vacuum packing in Agartala.", cite: "Charai Foods production note, 2025" },
      { kind: "h3", text: "Why still early stage" },
      { kind: "paragraph", text: "Six states sounds wide, but volumes are thin and the brand is unknown outside the region. The seed round is about deepening distribution in the markets it already serves rather than chasing new geographies." },
      { kind: "quote", text: "Everyone here already eats this. We are not creating a taste, we are making it safe to buy in a shop and trust.", cite: "Lalruatfela · Founder" },
    ],
    founders: [
      {
        name: "Lalruatfela",
        role: "Founder & CEO",
        bio: "From Aizawl, with a food-technology degree from Tezpur University and two years on a meat-processing line in Guwahati. Started Charai after watching home-smoked pork fail every formal-market test it was put to.",
        photoTreatment: "copper",
      },
    ],
    milestones: [
      { when: "Apr 2023", what: "Charai Foods founded", detail: "First controlled smokehouse set up in Agartala with two SKUs.", funded: false },
      { when: "Jul 2023", what: "FSSAI clearance secured", detail: "Process validated for ambient shelf-stable smoked pork.", funded: false },
      { when: "2023", what: "Saranya growth-stage entry", detail: "Joined the cohort and received a market-readiness grant.", funded: true },
      { when: "2024", what: "Three-state launch", detail: "Began retail distribution in Tripura, Mizoram and Assam.", funded: false },
      { when: "2024", what: "Smokehouse upgrade grant", detail: "NEATeHUB grant funded capacity expansion and vacuum-pack line.", funded: true },
      { when: "2025", what: "Six-state distribution", detail: "Extended reach to Nagaland, Meghalaya and Kolkata stockists.", funded: false },
      { when: "Jan 2026", what: "Seed round closed", detail: "Raised to deepen distribution and contract more rearing households.", funded: false },
    ],
    funding: [
      { round: "Growth grant", amount: "₹8,00,000", source: "RKVY RAFTAAR · Saranya", neatehubRole: "Lead grant & mentoring", date: "2023" },
      { round: "Capacity grant", amount: "₹6,50,000", source: "NEATeHUB food-processing fund", neatehubRole: "Direct disbursing body", date: "2024" },
      { round: "Seed", amount: "₹95,00,000", source: "Northeast angel syndicate", neatehubRole: "Diligence support & investor intro", date: "Jan 2026" },
    ],
    engagement: {
      quote: "Charai cracked the one thing that stops Northeast food brands scaling, which is making a traditional product pass formal safety standards without losing what people love about it.",
      manager: "Bhaskar Deb",
      role: "Programme Manager, Saranya",
      dates: "2023 — present",
      initials: "BD",
    },
    press: [
      { outlet: "EastMojo", headline: "Agartala startup brings shelf-stable smoked pork to formal retail", date: "Feb 2024", url: "#" },
      { outlet: "The Sangai Express", headline: "Charai Foods clears FSSAI, eyes six-state distribution", date: "Aug 2024", url: "#" },
      { outlet: "Mint", headline: "Northeast food brands chase the smoked-pork market", date: "Jan 2026", url: "#" },
    ],
    programTags: [
      { label: "Saranya · Growth stage", current: true },
    ],
    sdgs: [
      { num: 2, label: "Zero Hunger" },
      { num: 8, label: "Decent Work & Growth" },
    ],
  },
];
