export const VENTURES_B = [
  {
    name: "Naga Greens",
    slug: "naga-greens",
    sector: "Food",
    stage: "growth",
    year: 2022,
    program: "RKVY",
    location: "Dimapur, NL",
    oneLiner: "Naga king-chilli supply chain - direct from grower to processor.",
    photoTreatment: "copper",
    tagline: "Putting the world's hottest chilli on a traceable rail - from Naga hill plots straight to the spice processor's gate.",
    website: "nagagreens.in",
    founded: "Mar 2022",
    teamSize: 14,
    hq: "Dimapur, NL",
    status: "active",
    roundLabel: "Pre-Series A",
    roundDate: "Jan 2026",
    hiring: "3 open roles",
    investorContact: "imli@",
    facts: [
      { k: "Grower base", v: "1,240", sub: "registered chilli farmers across 6 districts" },
      { k: "Avg price uplift", v: "+34%", sub: "vs. local mandi rate, FY25" },
      { k: "Dried chilli moved", v: "210 MT", sub: "in the 2025 season" },
      { k: "GI-tagged lots", v: "100%", sub: "Naga King Chilli GI certified" },
      { k: "Repeat buyers", v: "9", sub: "spice processors on annual contract" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Building a price floor under the world's hottest chilli" },
      { kind: "paragraph", text: "The Naga king-chilli (Raja Mircha) carries a GI tag and global demand, yet for decades growers in the interior hills sold green pods to passing traders for whatever cash was on hand. Naga Greens replaced that scramble with a fixed-calendar procurement model: farmers know the buy price before they plant, and payment lands within 72 hours of weigh-in at a district collection shed." },
      { kind: "paragraph", text: "The harder problem was not demand but moisture. Improperly dried chilli loses both pungency and shelf value, so the company set up solar-assisted drying floors at three cluster points and trained women's self-help groups to grade by Scoville-relevant colour and skin integrity before lots are baled for processors." },
      { kind: "figure", text: "A grading shed at the Chumukedima cluster during the October flush, where SHG members sort dried pods by colour grade before baling.", cite: "Naga Greens field operations, 2025" },
      { kind: "h3", text: "Why the cold link mattered more than the cash" },
      { kind: "paragraph", text: "Once drying was standardised, processors began signing annual offtake contracts instead of buying spot, which let Naga Greens guarantee growers a season-ahead floor price. That single change - predictability rather than premium - is what pulled new farmers into the registry." },
      { kind: "quote", text: "Before this, I dried my chilli on the tin roof and prayed it wouldn't rain. Now I know my price in June and my money comes the same week I deliver.", cite: "Vikato Sumi · Grower, Zunheboto cluster" },
    ],
    founders: [
      {
        name: "Imlikumba Ao",
        role: "Co-founder & CEO",
        bio: "Grew up on a chilli and rice plot outside Mokokchung. Worked four years with a Dimapur agri-trading firm before starting Naga Greens to fix the grading and payment gap he watched his own family lose money to.",
        photoTreatment: "copper",
      },
      {
        name: "Bendangtila Jamir",
        role: "Co-founder & Head of Operations",
        bio: "Former ASRLM cluster coordinator in Tuensang district. Built the SHG drying-floor network and runs procurement logistics across the six-district grower base.",
        photoTreatment: "tea",
      },
    ],
    milestones: [
      { when: "Mar 2022", what: "Incorporated in Dimapur", detail: "Started with 80 growers across two Mokokchung clusters.", funded: false },
      { when: "Sep 2022", what: "First NEATeHUB RKVY grant", detail: "Seed grant funded the first solar drying floor and grading training.", funded: true },
      { when: "Jun 2023", what: "Crossed 500 registered growers", detail: "Added Zunheboto and Tuensang clusters.", funded: false },
      { when: "Feb 2024", what: "RKVY RAFTAAR growth-stage grant", detail: "Funded two additional drying clusters and a baling line.", funded: true },
      { when: "Nov 2024", what: "First annual offtake contracts", detail: "Five spice processors signed season-ahead procurement deals.", funded: false },
      { when: "Aug 2025", what: "210 MT season", detail: "Moved a record dried-chilli volume with 1,240 growers on the registry.", funded: false },
      { when: "Jan 2026", what: "Opened Pre-Series A", detail: "Raising to add a fines-and-flakes processing unit in Dimapur.", funded: false },
    ],
    funding: [
      { round: "Seed grant", amount: "Rs 18,00,000", source: "RKVY · MoA&FW", neatehubRole: "Direct grant", date: "Sep 2022" },
      { round: "Growth grant", amount: "Rs 40,00,000", source: "RKVY RAFTAAR · MoA&FW", neatehubRole: "Direct grant", date: "Feb 2024" },
      { round: "Angel", amount: "Rs 65,00,000", source: "NE Angel Collective", neatehubRole: "Introduced lead", date: "Oct 2024" },
      { round: "Pre-Series A", amount: "Rs 3,20,00,000 (target)", source: "Ankur Capital (lead)", neatehubRole: "Introduced lead", date: "Jan 2026" },
    ],
    engagement: {
      quote: "Naga Greens did the unglamorous work first - drying floors, grading, payment timelines - before chasing volume. That sequencing is why the processor contracts stuck.",
      manager: "Renchamo Kikon",
      role: "RKVY Program Manager, NEATeHUB",
      dates: "2022 - present",
      initials: "RK",
    },
    press: [
      { outlet: "EastMojo", headline: "How a Dimapur startup is fixing the king-chilli's broken supply chain", date: "Apr 2024", url: "#" },
      { outlet: "The Morung Express", headline: "GI-tagged Naga chilli finds steadier prices through grower network", date: "Nov 2024", url: "#" },
      { outlet: "Mongabay India", headline: "Solar drying floors give Nagaland chilli farmers a buffer against the rains", date: "Jul 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY RAFTAAR", current: true },
      { label: "RKVY Seed", current: false },
    ],
    sdgs: [
      { num: 1, label: "No Poverty" },
      { num: 8, label: "Decent Work & Economic Growth" },
      { num: 12, label: "Responsible Consumption & Production" },
    ],
  },
  {
    name: "Sirohi Dairy",
    slug: "sirohi-dairy",
    sector: "Livestock",
    stage: "early",
    year: 2024,
    program: "AIC",
    location: "Sivasagar, AS",
    oneLiner: "Smallholder dairy aggregation with chilling at every collection point.",
    photoTreatment: "default",
    tagline: "Cold milk from the very first kilometre - chilling units at the village shed, not three trucks later.",
    website: "sirohidairy.in",
    founded: "May 2024",
    teamSize: 9,
    hq: "Sivasagar, AS",
    status: "active",
    roundLabel: "Seed",
    roundDate: "Mar 2026",
    hiring: "2 open roles",
    investorContact: "nayan@",
    facts: [
      { k: "Collection points", v: "22", sub: "village sheds with bulk milk coolers" },
      { k: "Pourers", v: "640", sub: "smallholder dairy households" },
      { k: "Daily intake", v: "4,100 L", sub: "average, FY26 to date" },
      { k: "Rejection rate", v: "1.2%", sub: "down from 7% at start" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Chilling the milk before the heat can spoil it" },
      { kind: "paragraph", text: "In upper Assam's smallholder dairy belt, the gap between the morning milking and the nearest chilling plant is where most value evaporates - literally. Milk sitting in aluminium cans through a humid 35-degree morning sours before it is graded, and pourers absorb the loss. Sirohi Dairy's bet is simple: put a small bulk milk cooler at the village collection shed itself, so the cold chain starts at kilometre zero." },
      { kind: "paragraph", text: "Each cooler is paired with a fat-and-SNF analyser and a tablet, so a pourer's milk is tested, priced, and logged transparently at hand-over. Payments settle fortnightly to bank accounts, replacing the opaque cash-and-credit cycle that local middlemen ran." },
      { kind: "figure", text: "A 500-litre bulk milk cooler installed at the Demow collection shed, with the morning's pourers queued for fat testing.", cite: "Sirohi Dairy operations, 2025" },
      { kind: "h3", text: "Trust is built at the weighing scale" },
      { kind: "paragraph", text: "The transparent analyser did more for enrolment than any price promise. When pourers could see their own fat reading on the screen, monthly drop-outs fell and the daily intake roughly tripled within the first year." },
      { kind: "quote", text: "The cooler at our shed changed everything. My evening milk no longer turns by morning, and I am paid for exactly the fat I bring.", cite: "Junmoni Gogoi · Pourer, Demow shed" },
    ],
    founders: [
      {
        name: "Nayanmoni Saikia",
        role: "Founder & CEO",
        bio: "Daughter of a dairy household in Sivasagar district. Studied dairy technology at AAU Jorhat and worked a stint with a cooperative milk union before starting Sirohi to push chilling down to the village level.",
        photoTreatment: "default",
      },
    ],
    milestones: [
      { when: "May 2024", what: "Incorporated in Sivasagar", detail: "Launched with four collection sheds and 90 pourers.", funded: false },
      { when: "Aug 2024", what: "AIC NEATeHUB incubation grant", detail: "Funded the first six bulk milk coolers and analysers.", funded: true },
      { when: "Dec 2024", what: "Crossed 300 pourers", detail: "Daily intake reached 1,800 litres.", funded: false },
      { when: "May 2025", what: "AIC scale-up grant", detail: "Added ten more chilling sheds across Demow and Nazira blocks.", funded: true },
      { when: "Oct 2025", what: "Offtake tie-up signed", detail: "Regional processor contracted for daily chilled-milk supply.", funded: false },
      { when: "Feb 2026", what: "22 sheds, 640 pourers", detail: "Daily intake stabilised above 4,000 litres.", funded: false },
    ],
    funding: [
      { round: "Incubation grant", amount: "Rs 25,00,000", source: "AIC · NITI Aayog", neatehubRole: "Direct grant", date: "Aug 2024" },
      { round: "Scale-up grant", amount: "Rs 35,00,000", source: "AIC · NITI Aayog", neatehubRole: "Direct grant", date: "May 2025" },
      { round: "Seed", amount: "Rs 1,10,00,000 (target)", source: "Omnivore (in conversation)", neatehubRole: "Introduced lead", date: "Mar 2026" },
    ],
    engagement: {
      quote: "Sirohi understood that in dairy the loss is in the first hour, not the last mile. Pushing the cooler to the shed is capital-heavy but it is the right place to spend.",
      manager: "Pranab Hazarika",
      role: "AIC Program Manager, NEATeHUB",
      dates: "2024 - present",
      initials: "PH",
    },
    press: [
      { outlet: "The Assam Tribune", headline: "Sivasagar startup brings cold chain to the village milk shed", date: "Jan 2025", url: "#" },
      { outlet: "G Plus", headline: "How Sirohi Dairy is cutting milk spoilage for upper Assam smallholders", date: "Jun 2025", url: "#" },
      { outlet: "Pratidin Time", headline: "Transparent fat testing wins over Sivasagar dairy pourers", date: "Nov 2025", url: "#" },
    ],
    programTags: [
      { label: "AIC Incubation", current: true },
    ],
    sdgs: [
      { num: 2, label: "Zero Hunger" },
      { num: 8, label: "Decent Work & Economic Growth" },
    ],
  },
  {
    name: "Hilltop Coffee",
    slug: "hilltop-coffee",
    sector: "Food",
    stage: "early",
    year: 2024,
    program: "Saranya",
    location: "Aizawl, MZ",
    oneLiner: "Specialty coffee co-operative across 80 Mizoram smallholders.",
    photoTreatment: "default",
    tagline: "Shade-grown Mizo coffee, cup-scored and washed at origin - so the hill farmer keeps the specialty premium.",
    website: "hilltopcoffee.co.in",
    founded: "Jun 2024",
    teamSize: 7,
    hq: "Aizawl, MZ",
    status: "active",
    roundLabel: "Grant-funded",
    roundDate: "Sep 2025",
    hiring: "1 open role",
    investorContact: "lalrin@",
    facts: [
      { k: "Member growers", v: "80", sub: "smallholders across 5 villages" },
      { k: "Cupping score", v: "84.5", sub: "highest lot, 2025 washed Arabica" },
      { k: "Green coffee", v: "11 MT", sub: "processed in the 2025 harvest" },
      { k: "Price to grower", v: "+62%", sub: "vs. cherry sold to local traders" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "Treating Mizoram coffee as specialty, not commodity" },
      { kind: "paragraph", text: "Coffee has grown under the forest canopy in Mizoram's hills for years, but almost all of it left the state as unsorted cherry sold cheap to outside traders, stripping farmers of the specialty premium their altitude and shade actually earn. Hilltop Coffee organised 80 smallholders into a producer co-operative and moved the value-adding steps - pulping, washed fermentation, sun-drying on raised beds - to origin." },
      { kind: "paragraph", text: "A small central wet mill near Aizawl handles processing the village units cannot, and every lot is cup-scored before sale so buyers pay against a measured quality, not a guess. The co-operative structure means the milling margin flows back to members rather than to an intermediary." },
      { kind: "figure", text: "Washed Arabica drying on raised beds at the Hilltop central station outside Aizawl, hand-turned through the December dry spell.", cite: "Hilltop Coffee co-operative, 2025" },
      { kind: "h3", text: "The cupping table is the negotiating table" },
      { kind: "paragraph", text: "Scoring lots locally changed the conversation with roasters. An 84.5-point washed lot commands a price a sack of mixed cherry never could, and that single number is now what members chase each harvest." },
      { kind: "quote", text: "We always knew our coffee grew high and slow. We just never had a number to prove it was worth more. Now we do.", cite: "Lalrinawma Hauhnar · Founding member" },
    ],
    founders: [
      {
        name: "Lalrindiki Sailo",
        role: "Co-founder & Lead",
        bio: "From a Champhai-district farming family. Trained as a Q-grader after volunteering with a hill horticulture mission, and started Hilltop to bring origin processing - and cupping discipline - to Mizoram's smallholders.",
        photoTreatment: "default",
      },
      {
        name: "Vanlalruata Khiangte",
        role: "Co-founder & Field Lead",
        bio: "Former agriculture extension worker in Serchhip district. Runs grower training on selective picking and raised-bed drying across the five member villages.",
        photoTreatment: "tea",
      },
    ],
    milestones: [
      { when: "Jun 2024", what: "Co-operative registered in Aizawl", detail: "Started with 40 growers across two villages.", funded: false },
      { when: "Sep 2024", what: "Saranya growth-stage grant", detail: "NEATeHUB grant funded village pulping units and raised drying beds.", funded: true },
      { when: "Jan 2025", what: "First washed lots cup-scored", detail: "Top lot graded 83 points by an external Q-grader.", funded: false },
      { when: "May 2025", what: "Membership doubled to 80", detail: "Three more villages joined the co-operative.", funded: false },
      { when: "Sep 2025", what: "Saranya central-mill grant", detail: "Funded the central wet mill near Aizawl.", funded: true },
      { when: "Dec 2025", what: "11 MT harvest, 84.5 top score", detail: "First direct sale to a Bengaluru specialty roaster.", funded: false },
    ],
    funding: [
      { round: "Growth grant", amount: "Rs 22,00,000", source: "RKVY RAFTAAR Saranya · MoA&FW", neatehubRole: "Direct grant", date: "Sep 2024" },
      { round: "Infrastructure grant", amount: "Rs 30,00,000", source: "RKVY RAFTAAR Saranya · MoA&FW", neatehubRole: "Direct grant", date: "Sep 2025" },
      { round: "Working-capital loan", amount: "Rs 12,00,000", source: "Mizoram Rural Bank", neatehubRole: "Introduced lead", date: "Nov 2025" },
    ],
    engagement: {
      quote: "Hilltop refused the easy path of selling cherry by the sack. Moving processing and cupping to origin is slower, but it is the only way the premium reaches the grower.",
      manager: "Esther Lalremruati",
      role: "Saranya Program Manager, NEATeHUB",
      dates: "2024 - present",
      initials: "EL",
    },
    press: [
      { outlet: "The Northeast Today", headline: "A Mizoram co-operative is putting hill coffee on the specialty map", date: "Mar 2025", url: "#" },
      { outlet: "EastMojo", headline: "How Hilltop Coffee got Aizawl smallholders a 60 percent price jump", date: "Aug 2025", url: "#" },
      { outlet: "Vanglaini", headline: "Mizo washed Arabica scores 84.5, draws first direct roaster deal", date: "Dec 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY RAFTAAR Saranya", current: true },
    ],
    sdgs: [
      { num: 1, label: "No Poverty" },
      { num: 12, label: "Responsible Consumption & Production" },
      { num: 15, label: "Life on Land" },
    ],
  },
  {
    name: "Khasi Honey",
    slug: "khasi-honey",
    sector: "Food",
    stage: "growth",
    year: 2022,
    program: "RKVY",
    location: "Shillong, ML",
    oneLiner: "Single-origin honey, FSSAI-certified, exporting to Singapore.",
    photoTreatment: "copper",
    tagline: "Forest-floral honey from the Khasi hills, traced hive-to-jar and cleared for the export shelf.",
    website: "khasihoney.in",
    founded: "Aug 2022",
    teamSize: 16,
    hq: "Shillong, ML",
    status: "active",
    roundLabel: "Seed",
    roundDate: "Feb 2026",
    hiring: "2 open roles",
    investorContact: "ban@",
    facts: [
      { k: "Beekeepers", v: "430", sub: "across East & West Khasi Hills" },
      { k: "Single-origin SKUs", v: "6", sub: "by forest floral source" },
      { k: "Honey processed", v: "48 MT", sub: "in FY25" },
      { k: "Export markets", v: "2", sub: "Singapore live, UAE in pilot" },
      { k: "Lab-tested batches", v: "100%", sub: "NMR-screened for purity" },
    ],
    body: [
      { kind: "eyebrow", text: "The work" },
      { kind: "h2", text: "From mixed-lot honey to a traceable single-origin shelf" },
      { kind: "paragraph", text: "The Khasi hills produce some of the country's most distinctive forest honey, but most of it was pooled into anonymous bulk lots and sold to repackers who captured both the margin and the story. Khasi Honey rebuilt the chain around traceability: each beekeeper's harvest is logged by location and floral season, and lots are kept separate so a jar of wild-bee forest honey can be told apart from a sweet-clover spring batch." },
      { kind: "paragraph", text: "Getting onto an export shelf meant clearing the hard gates - FSSAI certification, moisture control, and NMR testing to prove the honey is unadulterated. The company set up a central extraction and bottling unit in Shillong with a moisture-reduction line, then certified its process end to end." },
      { kind: "figure", text: "The Shillong bottling line filling single-origin forest honey, each batch tagged to its source cluster before NMR screening.", cite: "Khasi Honey operations, 2025" },
      { kind: "h3", text: "Certification was the export passport" },
      { kind: "paragraph", text: "The first Singapore order came only after NMR-backed purity reports were in hand. For a category drowning in adulteration claims, a verifiable test result did more to open the export door than any tasting note." },
      { kind: "quote", text: "Buyers abroad do not want a story first, they want a lab report. Once we could hand them clean NMR data, the conversation moved fast.", cite: "Banshanlang Lyngdoh · Co-founder" },
    ],
    founders: [
      {
        name: "Banshanlang Lyngdoh",
        role: "Co-founder & CEO",
        bio: "From a beekeeping family in the East Khasi Hills. Worked with a Meghalaya horticulture mission before starting Khasi Honey to move local apiarists from bulk supply to a branded, export-ready product.",
        photoTreatment: "copper",
      },
      {
        name: "Daiahun Suchiang",
        role: "Co-founder & Quality Lead",
        bio: "Food-technology graduate from Shillong who built the moisture-control and NMR-testing protocols. Manages FSSAI compliance and the export documentation chain.",
        photoTreatment: "default",
      },
    ],
    milestones: [
      { when: "Aug 2022", what: "Incorporated in Shillong", detail: "Started with 110 beekeepers in the East Khasi Hills.", funded: false },
      { when: "Nov 2022", what: "NEATeHUB RKVY seed grant", detail: "Funded the first extraction and bottling unit.", funded: true },
      { when: "Jul 2023", what: "FSSAI certification secured", detail: "Process certified end to end for branded retail.", funded: false },
      { when: "Mar 2024", what: "RKVY RAFTAAR growth grant", detail: "Funded the moisture-reduction line and NMR testing tie-up.", funded: true },
      { when: "Sep 2024", what: "First Singapore export order", detail: "Single-origin forest honey shipped under own label.", funded: false },
      { when: "Jun 2025", what: "430 beekeepers, 48 MT processed", detail: "Six single-origin SKUs on shelf, UAE pilot opened.", funded: false },
      { when: "Feb 2026", what: "Opened Seed round", detail: "Raising to expand the Shillong unit and add a second drying line.", funded: false },
    ],
    funding: [
      { round: "Seed grant", amount: "Rs 20,00,000", source: "RKVY · MoA&FW", neatehubRole: "Direct grant", date: "Nov 2022" },
      { round: "Growth grant", amount: "Rs 45,00,000", source: "RKVY RAFTAAR · MoA&FW", neatehubRole: "Direct grant", date: "Mar 2024" },
      { round: "Angel", amount: "Rs 80,00,000", source: "NE Angel Collective", neatehubRole: "Introduced lead", date: "Jan 2025" },
      { round: "Seed", amount: "Rs 2,50,00,000 (target)", source: "Aavishkaar Capital (lead)", neatehubRole: "Introduced lead", date: "Feb 2026" },
    ],
    engagement: {
      quote: "Khasi Honey spent its first year on certification and testing instead of marketing. That discipline is exactly why the export shelf opened when others stalled at the customs gate.",
      manager: "Wanphrang Kharkongor",
      role: "RKVY Program Manager, NEATeHUB",
      dates: "2022 - present",
      initials: "WK",
    },
    press: [
      { outlet: "The Shillong Times", headline: "Single-origin Khasi honey clears FSSAI, eyes the export market", date: "Sep 2023", url: "#" },
      { outlet: "EastMojo", headline: "Meghalaya honey startup ships first branded lot to Singapore", date: "Oct 2024", url: "#" },
      { outlet: "Business North East", headline: "How NMR testing got Khasi Honey onto an export shelf", date: "Jul 2025", url: "#" },
    ],
    programTags: [
      { label: "RKVY RAFTAAR", current: true },
      { label: "RKVY Seed", current: false },
    ],
    sdgs: [
      { num: 8, label: "Decent Work & Economic Growth" },
      { num: 12, label: "Responsible Consumption & Production" },
      { num: 15, label: "Life on Land" },
    ],
  },
];
