export const INSIGHTS_GEN = [
  {
    title: "Tea bio-stimulants: where the unit economics actually break.",
    slug: "tea-bio-stimulants-unit-economics",
    channel: "insights",
    category: "Sector",
    section: "Field Notes",
    dek: "Bio-stimulant pilots on Assam tea read well at the demo plot and stall the moment they cross a few hundred bushes. The break isn't agronomy — it's the cost of getting a litre of product onto a leaf.",
    date: "12 Apr 2026",
    readTime: "7 min read",
    featured: false,
    photoTreatment: "tea",
    heroPhotoLabel: "PHOTO: Pluckers working a mature tea section at first flush, mist in the valley behind, eye-level mid-shot.",
    heroCaption: "First flush in a smallholder section near Dibrugarh, where most bio-stimulant trials begin and few survive.",
    author: {
      name: "Ananya Gogoi",
      role: "Sector Analyst, Plantation Crops · NEATeHUB",
      initials: "AG",
      bio: "Tracks tea and horticulture ventures across the Upper Assam belt. Spent four seasons with KVK Dibrugarh on input-efficiency trials before joining the hub.",
    },
    body: [
      { kind: "paragraph", text: "Almost every tea bio-stimulant founder we meet has the same slide: a side-by-side photo of two bushes, one visibly greener, with a yield bump quoted somewhere between 9 and 14 percent. The agronomy is usually real. The demo plot is usually honest. And then the pilot crosses roughly the 200-bush mark and the numbers quietly stop working." },
      { kind: "paragraph", text: "We've now watched this happen across six ventures over three seasons, so it's worth writing down where exactly the economics break — because it is almost never where the founder expects." },
      { kind: "h2", text: "The litre-on-leaf problem" },
      { kind: "paragraph", text: "A bio-stimulant is cheap to manufacture and expensive to apply. At demo scale a founder or a field officer sprays the plot themselves, so the application labour is invisible. At 200 bushes that labour becomes a real line item, and on smallholder sections — which dominate the Assam belt — there is no spare labour to absorb it during plucking season." },
      { kind: "paragraph", text: "So the founder either pays for dedicated spraying, which erases the margin, or they fold application into the plucking round, which the estate refuses because it slows the pluckers down. Either way the unit cost per bush roughly triples between the demo and the first paying section." },
      { kind: "stat", stats: [
        { num: "200", lbl: "bushes — where most pilots stall" },
        { num: "3.1x", lbl: "median jump in cost-per-bush from demo to paid section" },
        { num: "9–14%", lbl: "yield uplift claimed at demo scale" },
      ] },
      { kind: "paragraph", text: "The yield uplift is genuine. It just doesn't cover a tripled application cost on a crop where the grower already operates on a thin green-leaf price." },
      { kind: "figure", text: "Knapsack application on a fringe smallholder section — the labour that's invisible at demo scale and decisive at 200 bushes.", cite: "PHOTO: Field officer with a knapsack sprayer mid-section, early morning, low-angle.", photoTreatment: "tea" },
      { kind: "h3", text: "What the survivors did differently" },
      { kind: "paragraph", text: "The two ventures that pushed past the 200-bush wall both stopped selling a litre and started selling a per-acre service folded into an existing visit the grower already pays for — a soil-test round, a pruning crew. Application stopped being a new cost and became a rider on an old one. That reframing, not a better formulation, is what moved the unit economics." },
      { kind: "quote", text: "We spent a year improving the product. The thing that actually unlocked scale was deleting the spray day from the grower's calendar entirely.", cite: "Founder · second-season bio-stimulant pilot, Sivasagar" },
      { kind: "paragraph", text: "The lesson for the next cohort is blunt: model the application labour before the agronomy. If your spreadsheet assumes the founder is holding the sprayer, you don't have a unit economic — you have a demo." },
    ],
    footnotes: [
      { text: "Figures aggregate six bio-stimulant pilots reviewed by NEATeHUB between 2023 and 2025; smallholder sections defined as under five hectares per the KVK Dibrugarh classification." },
    ],
  },

  {
    title: "Saranya '25 retrospective: what worked, what we changed.",
    slug: "saranya-25-retrospective",
    channel: "insights",
    category: "Program",
    section: "Program Notes",
    dek: "Half the 2025 Saranya cohort exceeded their growth milestones, two ventures pivoted hard, and two paused. Here's what we read from the spread — and the three things we're changing for '26.",
    date: "28 Mar 2026",
    readTime: "8 min read",
    featured: false,
    photoTreatment: "default",
    heroPhotoLabel: "PHOTO: Saranya cohort founders mid-discussion around a long table at the AAU incubation floor, natural light, candid.",
    heroCaption: "The 2025 Saranya cohort during a mid-programme review at the Jorhat incubation floor.",
    author: {
      name: "Rituraj Bezbaruah",
      role: "Saranya Programme Lead · NEATeHUB",
      initials: "RB",
      bio: "Runs the growth-stage Saranya programme. Former operations lead at a Guwahati agri-logistics firm; mentors on go-to-market and FPO partnerships.",
    },
    body: [
      { kind: "paragraph", text: "Saranya is our growth-stage sub-programme — ventures that already have a product in the field and are trying to get to repeatable revenue. The 2025 cohort was twelve companies. We promised them honesty at the start, so we owe the same in public: not everyone made it to their milestones, and that's the point of writing this down." },
      { kind: "paragraph", text: "Six of the twelve exceeded the growth targets we set together. Two pivoted their core model mid-programme. Two paused operations. The remaining two landed roughly on plan. The interesting signal is in the spread, not the average." },
      { kind: "h2", text: "What worked" },
      { kind: "paragraph", text: "The six that over-delivered shared one trait: they entered Saranya with a paying customer already nagging them for more, not a customer they still had to find. Our cohort, in other words, didn't create demand — it removed the bottlenecks in front of demand that already existed. When we tried to push growth on ventures still hunting for their first repeat buyer, the programme couldn't manufacture what wasn't there." },
      { kind: "stat", stats: [
        { num: "6 of 12", lbl: "exceeded growth milestones" },
        { num: "2", lbl: "pivoted core model mid-programme" },
        { num: "₹4.1 Cr", lbl: "follow-on capital raised across the cohort" },
      ] },
      { kind: "paragraph", text: "The two pivots were not failures. Both ventures arrived selling hardware and left selling a service wrapped around that hardware — a shift we now actively coach toward, because owning the recurring relationship beats owning the box in almost every Northeast supply chain we've studied." },
      { kind: "h3", text: "What we changed for '26" },
      { kind: "list", items: [
        { text: "Moved the demand-validation gate before admission, not into week three — we won't admit a growth-stage venture that can't show a repeat buyer." },
        { text: "Replaced the single mid-programme review with a fortnightly metric check-in, so a stall is caught in weeks, not at the showcase." },
        { text: "Added a structured pause option with a re-entry path, so the two paused ventures don't read as exits — they read as deferred." },
      ] },
      { kind: "quote", text: "The retrospective made us comfortable saying a venture wasn't ready for Saranya yet. That's a kinder answer than admitting them and watching the programme fail to help.", cite: "Rituraj Bezbaruah · Saranya Programme Lead" },
      { kind: "paragraph", text: "We'll run the same honest tally at the end of '26. If the changes work, the pivots should happen earlier and the pauses should turn into re-entries. If they don't, we'll write that down too." },
    ],
    footnotes: [
      { text: "Milestone definitions are set per venture at admission and are not standardised across the cohort; the six/two/two/two split reflects performance against each venture's own targets." },
    ],
  },

  {
    title: "Aquaculture sensing in the Northeast: a five-year scan.",
    slug: "aquaculture-sensing-five-year-scan",
    channel: "insights",
    category: "Sector",
    section: "Field Notes",
    dek: "We looked at every pond-sensing venture we've encountered since 2021. The hardware almost always works in the lab and almost always fails in the pond — and the reasons rhyme.",
    date: "15 Feb 2026",
    readTime: "9 min read",
    featured: false,
    photoTreatment: "copper",
    heroPhotoLabel: "PHOTO: Smallholder fish pond at dawn with a floating sensor buoy, reflections on still water, wide shot.",
    heroCaption: "A trial dissolved-oxygen buoy on a composite-culture pond near Nagaon — three weeks before biofouling took it offline.",
    author: {
      name: "Manash Pratim Das",
      role: "Sector Analyst, Aquaculture · NEATeHUB",
      initials: "MD",
      bio: "Covers inland fisheries and aquaculture ventures across Assam and the hill states. Trained as an aquaculture engineer; worked on pond-management trials with a Nagaon FPO before joining the hub.",
    },
    body: [
      { kind: "paragraph", text: "Inland aquaculture is one of the Northeast's quieter growth stories — composite carp culture across thousands of smallholder ponds in Assam alone. So sensing startups keep arriving, promising dissolved-oxygen and ammonia monitoring that would let a farmer dose feed and aeration precisely instead of by feel." },
      { kind: "paragraph", text: "We pulled together every pond-sensing venture we've met since 2021 — eleven of them — and read the arc. The pattern is depressingly consistent: the device passes its bench test, gets deployed, and is dead or ignored within a season. It is almost never the sensor chemistry that kills it." },
      { kind: "h2", text: "Three failure modes that keep recurring" },
      { kind: "paragraph", text: "First, biofouling. A Northeast pond is warm, nutrient-rich, and biologically busy. An optical dissolved-oxygen probe that's accurate in clean water drifts badly within two to three weeks as algae and silt coat the membrane. Founders budget for the sensor and forget the cleaning regime, so the data goes quietly wrong rather than visibly absent — the worst kind of failure." },
      { kind: "paragraph", text: "Second, power and connectivity. Ponds sit where the grid is weakest and the mobile signal is thinnest. Solar plus a low-power radio is the only honest answer, and the ventures that skipped it lost the device to a flat battery before they lost it to fouling." },
      { kind: "stat", stats: [
        { num: "11", lbl: "pond-sensing ventures scanned since 2021" },
        { num: "2–3 wks", lbl: "median time to meaningful biofouling drift" },
        { num: "1 of 11", lbl: "still operating at the same site after a year" },
      ] },
      { kind: "paragraph", text: "Third, and most fatal: the farmer doesn't act on the reading. A dissolved-oxygen number means nothing without a clear, affordable action attached — turn on the aerator, hold the feed. Most ventures shipped a dashboard and assumed behaviour change. It didn't come." },
      { kind: "figure", text: "Biofouling on a retrieved probe after eighteen days in a nutrient-rich pond — the failure mode nobody budgets for.", cite: "PHOTO: Close-up of an algae-coated sensor membrane in a gloved hand, harsh daylight.", photoTreatment: "copper" },
      { kind: "h3", text: "What the one survivor got right" },
      { kind: "paragraph", text: "The single venture still running at its original site stopped selling readings and started selling an aeration decision. The sensor triggers the aerator automatically and only messages the farmer when it has acted. The data became invisible; the action became the product. Crucially, they also built a thirty-second weekly wipe-down into the farmer's routine and paid for it with a tiny per-pond subscription." },
      { kind: "quote", text: "We stopped shipping a number to a screen. The farmer doesn't want a dissolved-oxygen graph — they want the aerator to come on before the fish gasp.", cite: "Founder · the one pond-sensing venture still live at its first site" },
      { kind: "paragraph", text: "For the next aquaculture founder reading this: assume your sensor will foul, assume the grid will fail, and assume the farmer will ignore a dashboard. Design for all three from day one, or your bench test is the high point of the company." },
    ],
    footnotes: [
      { text: "Scan covers ventures encountered through NEATeHUB programmes and partner referrals; it is not an exhaustive census of Northeast aquaculture-tech activity." },
      { text: "Composite culture refers to the polyculture of compatible carp species in a shared pond, the dominant smallholder model across the Assam plains." },
    ],
  },

  {
    title: "From AAU classroom to ₹3.2Cr raise: the Kaziranga Bio story.",
    slug: "kaziranga-bio-story",
    channel: "insights",
    category: "Founder Story",
    section: "Founder Story",
    dek: "A six-year arc, told by the founder — from a final-year AAU project on microbial soil inoculants to a ₹3.2 crore raise and a manufacturing line outside Jorhat.",
    date: "02 Feb 2026",
    readTime: "8 min read",
    featured: false,
    photoTreatment: "default",
    heroPhotoLabel: "PHOTO: Kaziranga Bio founder on the factory floor beside the fermentation tanks, environmental portrait, eye-level, natural light.",
    heroCaption: "Dipankar Saikia at the Kaziranga Bio fermentation line outside Jorhat, six years after the idea was a classroom assignment.",
    author: {
      name: "Priyam Hazarika",
      role: "Editorial Lead · NEATeHUB",
      initials: "PH",
      bio: "Writes the founder-story series. Former regional business reporter based in Guwahati covering agriculture and rural enterprise.",
    },
    body: [
      { kind: "paragraph", text: "Dipankar Saikia is clear that Kaziranga Bio began as a way to pass a course. In his final year of agricultural microbiology at AAU Jorhat, the assignment was to isolate a soil microbe with a practical use. He isolated a phosphate-solubilising strain from a tea-garden soil sample and, almost as an afterthought, wondered whether it could replace part of a smallholder's fertiliser bill." },
      { kind: "paragraph", text: "Six years later that afterthought is a company with a fermentation line, eleven employees, and a ₹3.2 crore raise behind it. This is his account of the arc, lightly edited." },
      { kind: "h2", text: "The years nobody photographs" },
      { kind: "paragraph", text: "The classroom-to-company story is usually told as a leap. Saikia insists it was a crawl. The strain worked in the lab in year one. It took until year three to make it survive in a packet on a dealer's shelf in Assam humidity — a shelf-life problem that nearly ended the company twice." },
      { kind: "paragraph", text: "He came into NEATeHUB at the idea stage through Isanya, the residential sub-programme, where the push was less about the science and more about whether a farmer would actually pay. The honest answer at the time was: not yet, not reliably. That gap defined the next two years." },
      { kind: "stat", stats: [
        { num: "6 yrs", lbl: "from classroom isolate to ₹3.2 Cr raise" },
        { num: "₹3.2 Cr", lbl: "total capital raised, incl. grant" },
        { num: "11", lbl: "people on the Jorhat line today" },
      ] },
      { kind: "paragraph", text: "The turn came when he stopped selling a yield promise and started selling a fertiliser-cost reduction the farmer could verify in one season. A smaller, provable claim beat a bigger, unprovable one — and the dealers, who had been the bottleneck, finally stocked it because returns dropped." },
      { kind: "h3", text: "What the raise actually bought" },
      { kind: "paragraph", text: "The ₹3.2 crore wasn't for growth marketing. Most of it went into the fermentation and packaging line outside Jorhat that fixed the shelf-life problem at scale — the unglamorous infrastructure that the classroom version never imagined needing. Saikia is candid that the science was the easy 20 percent." },
      { kind: "figure", text: "The packaging line that fixed the shelf-life problem — the part of the company the founder says he most underestimated.", cite: "PHOTO: Automated sachet-filling line with workers, factory interior, daylight through high windows.", photoTreatment: "default" },
      { kind: "quote", text: "I thought the hard part was the microbe. The hard part was a sachet that still works after three months on a dealer's shelf in a Jorhat July.", cite: "Dipankar Saikia · Founder, Kaziranga Bio" },
      { kind: "paragraph", text: "Asked what he'd tell the version of himself in that final-year lab, he doesn't mention the science at all. He says he'd tell him to go and stand in a fertiliser dealer's shop for a week first, and only then decide what to isolate." },
    ],
    footnotes: [
      { text: "Kaziranga Bio is a NEATeHUB portfolio venture; figures are founder-reported and include grant capital deployed through RKVY RAFTAAR." },
    ],
  },

  {
    title: "How we evaluate idea-stage applications. Inside the Isanya scorecard.",
    slug: "isanya-scorecard",
    channel: "insights",
    category: "Method",
    section: "Method",
    dek: "We're publishing the scorecard our reviewers use on idea-stage Isanya applications, so founders can self-assess honestly before they apply — and so the process is legible, not a black box.",
    date: "20 Jan 2026",
    readTime: "6 min read",
    featured: false,
    photoTreatment: "tea",
    heroPhotoLabel: "PHOTO: Two reviewers reading printed applications across a table at the AAU incubation floor, overhead soft light, candid.",
    heroCaption: "An Isanya review round in progress — the process we're now putting on paper for applicants.",
    author: {
      name: "Sneha Kalita",
      role: "Isanya Programme Lead · NEATeHUB",
      initials: "SK",
      bio: "Leads the idea-stage, residential Isanya sub-programme. Background in design research; built the current application scorecard with the review panel.",
    },
    body: [
      { kind: "paragraph", text: "Isanya is our idea-stage, residential sub-programme — founders who have a problem and a hunch, not yet a product. Selection is the most consequential thing we do, and until now the criteria lived in reviewers' heads. That's not fair to applicants, so we're publishing the scorecard." },
      { kind: "paragraph", text: "The goal isn't to game-proof the process. It's the opposite: if a founder reads this and decides not to apply yet, the scorecard has done its job. We'd rather lose a premature application than waste a residential slot." },
      { kind: "h2", text: "The four things we actually score" },
      { kind: "paragraph", text: "We don't score the idea's novelty and we don't score the pitch deck. We've learned both are weak predictors of who thrives in a residential idea-stage programme. We score four things, each out of five, weighted as below." },
      { kind: "list", items: [
        { text: "Problem proximity (×3): has the founder lived close to this problem? A founder from a tea-belt family solving a tea problem outscores a polished outsider every time." },
        { text: "Evidence of motion (×2): have they already done something — a clumsy prototype, ten farmer conversations — without anyone asking them to?" },
        { text: "Coachability (×2): in the interview, do they update when challenged, or defend? Residential programmes amplify whichever trait you arrive with." },
        { text: "Founder-region fit (×1): can they credibly operate in the Northeast field conditions the venture demands, not just describe them?" },
      ] },
      { kind: "stat", stats: [
        { num: "×3", lbl: "weight on problem proximity — the heaviest factor" },
        { num: "40", lbl: "max score after weighting" },
        { num: "26", lbl: "rough threshold for a residential slot" },
      ] },
      { kind: "paragraph", text: "Notice what's missing: we don't score how big the market is or how impressive the team's CVs are. At idea stage those are guesses dressed as analysis. Proximity, motion, and coachability are observable now and predict who'll still be standing in six months." },
      { kind: "h3", text: "How to self-assess before you apply" },
      { kind: "paragraph", text: "Score yourself honestly on the four axes. If your weakest line is problem proximity, the fix isn't a better application — it's spending a season closer to the problem. If it's evidence of motion, go do the clumsy version of your idea this month and apply next cycle. The scorecard is most useful as a to-do list, not a test." },
      { kind: "quote", text: "Publishing the rubric cost us nothing and gave applicants a mirror. The strongest cohort we've selected is the one that self-screened before they reached us.", cite: "Sneha Kalita · Isanya Programme Lead" },
      { kind: "paragraph", text: "We'll revise the weights as we learn. If proximity stops predicting outcomes, we'll change it and say so. A scorecard that never changes is one nobody is checking against reality." },
    ],
    footnotes: [
      { text: "Weights and thresholds are reviewed each cycle and may differ slightly for a given Isanya intake; the version above reflects the early-2026 round." },
    ],
  },

  {
    title: "FY25 Impact Report: 70 funded, ₹7.2Cr deployed, what it bought.",
    slug: "fy25-impact-report",
    channel: "insights",
    category: "Report",
    section: "Report",
    dek: "The full FY25 numbers, the methodology behind them, and an honest read of what ₹7.2 crore across seventy ventures actually moved on the ground — and what it didn't.",
    date: "10 Jan 2026",
    readTime: "9 min read",
    featured: false,
    photoTreatment: "copper",
    heroPhotoLabel: "PHOTO: Aggregation point at an FPO with crates being weighed, founders and farmers together, golden hour, wide environmental shot.",
    heroCaption: "An FPO aggregation point served by two FY25-funded ventures — the kind of ground the report tries to measure.",
    author: {
      name: "Bhaskar Jyoti Nath",
      role: "Impact & Reporting Lead · NEATeHUB",
      initials: "BN",
      bio: "Owns NEATeHUB's measurement and reporting. Former monitoring-and-evaluation specialist on a state rural-livelihoods programme.",
    },
    body: [
      { kind: "paragraph", text: "In FY25 we funded seventy ventures and deployed ₹7.2 crore across grants and facilitated capital. Those two numbers are easy to put on a banner. This report is about what they bought — and we've tried to write it so a funder can audit the methodology, not just admire the totals." },
      { kind: "paragraph", text: "We'll start with the headline figures, then spend most of the report on how we counted, because an impact number without its method is just a press release." },
      { kind: "h2", text: "The headline numbers" },
      { kind: "stat", stats: [
        { num: "70", lbl: "ventures funded in FY25" },
        { num: "₹7.2 Cr", lbl: "deployed — grants plus facilitated capital" },
        { num: "31,000+", lbl: "farmers reached by funded ventures" },
      ] },
      { kind: "paragraph", text: "Of the seventy, forty-one were idea or early stage and twenty-nine were growth stage. The capital skewed toward growth — roughly two-thirds of the rupees went to the twenty-nine, which is deliberate: growth-stage rupees move more ground per rupee, while idea-stage support is mostly non-financial." },
      { kind: "h3", text: "How we counted — and where we don't" },
      { kind: "paragraph", text: "Farmers reached is a deduplicated count of cultivators who transacted with a funded venture during FY25, self-reported by ventures and spot-audited on a sample. We do not claim attribution for income change, because we cannot cleanly separate our ventures' effect from weather, price, and policy in a single year. Anyone who quotes you a precise income-uplift figure from a one-year agri programme is selling you something." },
      { kind: "list", items: [
        { text: "Counted: farmers transacting, capital deployed, follow-on capital raised, jobs at funded ventures, FPOs partnered." },
        { text: "Not counted as impact: income uplift, yield change, emissions avoided — too confounded to claim honestly at this horizon." },
        { text: "Spot-audited: a 15 percent sample of self-reported farmer counts, verified against venture transaction records." },
      ] },
      { kind: "figure", text: "A funded cold-chain node at an FPO — the kind of asset that's countable, against the income effects that aren't.", cite: "PHOTO: Solar cold-storage unit at a collection point with staged produce, daylight, wide.", photoTreatment: "copper" },
      { kind: "paragraph", text: "What the ₹7.2 crore most visibly bought was infrastructure that persists past FY25 — cold-chain nodes, processing lines, sensing networks — and follow-on capital, with funded ventures raising a further ₹11 crore from outside investors during the year. That leverage ratio matters more to us than the gross deployment figure." },
      { kind: "quote", text: "We'd rather under-claim and be trusted than over-claim and be quoted. The methodology section is the report; the headline is just the door.", cite: "Bhaskar Jyoti Nath · Impact & Reporting Lead" },
      { kind: "paragraph", text: "What it didn't buy is equally worth saying: durable jobs at idea-stage ventures remained thin, and our reach into the hill states stayed below where we want it. Those are the two lines we're holding ourselves to in FY26." },
    ],
    footnotes: [
      { text: "Figures cover the financial year ending March 2025; facilitated capital includes investor rounds that NEATeHUB introduced or co-invested in but excludes capital raised with no hub involvement." },
      { text: "Farmer-reach counts are self-reported by ventures with a 15 percent independent spot-audit; the full methodology note is available with the downloadable report." },
    ],
  },
];
